/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AlbumsIndexRouteImport } from './routes/albums.index'
import { Route as AlbumsSlugRouteImport } from './routes/albums.$slug'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as FocusAreasIndexRouteImport } from './routes/focus-areas.index'
import { Route as FocusAreasSlugRouteImport } from './routes/focus-areas.$slug'
import { Route as FormsSlugRouteImport } from './routes/forms.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsMapRouteImport } from './routes/projects.map'
import { Route as TeamIdRouteImport } from './routes/team.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'
import { Route as AuthenticatedAdminAlbumsRouteImport } from './routes/_authenticated/admin.albums'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin.branding'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminFocusAreasRouteImport } from './routes/_authenticated/admin.focus-areas'
import { Route as AuthenticatedAdminFormsRouteImport } from './routes/_authenticated/admin.forms'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin.homepage'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin.menu'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin.stats'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin.tags'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminVideoAlbumsRouteImport } from './routes/_authenticated/admin.video-albums'
import { Route as AuthenticatedAdminFormsIndexRouteImport } from './routes/_authenticated/admin.forms.index'
import { Route as AuthenticatedAdminFormsIdIndexRouteImport } from './routes/_authenticated/admin.forms.$id.index'
import { Route as AuthenticatedAdminFormsIdSubmissionsRouteImport } from './routes/_authenticated/admin.forms.$id.submissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsSlugRoute = AlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusAreasIndexRoute = FocusAreasIndexRouteImport.update({
  id: '/focus-areas/',
  path: '/focus-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusAreasSlugRoute = FocusAreasSlugRouteImport.update({
  id: '/focus-areas/$slug',
  path: '/focus-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSlugRoute = FormsSlugRouteImport.update({
  id: '/forms/$slug',
  path: '/forms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMapRoute = ProjectsMapRouteImport.update({
  id: '/projects/map',
  path: '/projects/map',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdRoute = TeamIdRouteImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAlbumsRoute =
  AuthenticatedAdminAlbumsRouteImport.update({
    id: '/admin/albums',
    path: '/admin/albums',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/admin/articles',
    path: '/admin/articles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/admin/branding',
    path: '/admin/branding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/admin/contact',
    path: '/admin/contact',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/admin/documents',
    path: '/admin/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFocusAreasRoute =
  AuthenticatedAdminFocusAreasRouteImport.update({
    id: '/admin/focus-areas',
    path: '/admin/focus-areas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFormsRoute = AuthenticatedAdminFormsRouteImport.update({
  id: '/admin/forms',
  path: '/admin/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/admin/homepage',
    path: '/admin/homepage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/admin/partners',
    path: '/admin/partners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/admin/projects',
    path: '/admin/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminVideoAlbumsRoute =
  AuthenticatedAdminVideoAlbumsRouteImport.update({
    id: '/admin/video-albums',
    path: '/admin/video-albums',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFormsIndexRoute =
  AuthenticatedAdminFormsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminFormsRoute,
  } as any)
const AuthenticatedAdminFormsIdIndexRoute =
  AuthenticatedAdminFormsIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedAdminFormsRoute,
  } as any)
const AuthenticatedAdminFormsIdSubmissionsRoute =
  AuthenticatedAdminFormsIdSubmissionsRouteImport.update({
    id: '/$id/submissions',
    path: '/$id/submissions',
    getParentRoute: () => AuthenticatedAdminFormsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/setup': typeof SetupRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/focus-areas/$slug': typeof FocusAreasSlugRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/map': typeof ProjectsMapRoute
  '/team/$id': typeof TeamIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/focus-areas/': typeof FocusAreasIndexRoute
  '/news/': typeof NewsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/albums': typeof AuthenticatedAdminAlbumsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/focus-areas': typeof AuthenticatedAdminFocusAreasRoute
  '/admin/forms': typeof AuthenticatedAdminFormsRouteWithChildren
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/video-albums': typeof AuthenticatedAdminVideoAlbumsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/forms/': typeof AuthenticatedAdminFormsIndexRoute
  '/admin/forms/$id/submissions': typeof AuthenticatedAdminFormsIdSubmissionsRoute
  '/admin/forms/$id/': typeof AuthenticatedAdminFormsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/setup': typeof SetupRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/focus-areas/$slug': typeof FocusAreasSlugRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/map': typeof ProjectsMapRoute
  '/team/$id': typeof TeamIdRoute
  '/albums': typeof AlbumsIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/focus-areas': typeof FocusAreasIndexRoute
  '/news': typeof NewsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/albums': typeof AuthenticatedAdminAlbumsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/focus-areas': typeof AuthenticatedAdminFocusAreasRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/video-albums': typeof AuthenticatedAdminVideoAlbumsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/forms': typeof AuthenticatedAdminFormsIndexRoute
  '/admin/forms/$id/submissions': typeof AuthenticatedAdminFormsIdSubmissionsRoute
  '/admin/forms/$id': typeof AuthenticatedAdminFormsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/setup': typeof SetupRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/focus-areas/$slug': typeof FocusAreasSlugRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/map': typeof ProjectsMapRoute
  '/team/$id': typeof TeamIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/focus-areas/': typeof FocusAreasIndexRoute
  '/news/': typeof NewsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/albums': typeof AuthenticatedAdminAlbumsRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/focus-areas': typeof AuthenticatedAdminFocusAreasRoute
  '/_authenticated/admin/forms': typeof AuthenticatedAdminFormsRouteWithChildren
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/video-albums': typeof AuthenticatedAdminVideoAlbumsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/forms/': typeof AuthenticatedAdminFormsIndexRoute
  '/_authenticated/admin/forms/$id/submissions': typeof AuthenticatedAdminFormsIdSubmissionsRoute
  '/_authenticated/admin/forms/$id/': typeof AuthenticatedAdminFormsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/partners'
    | '/reset-password'
    | '/resources'
    | '/setup'
    | '/albums/$slug'
    | '/articles/$slug'
    | '/focus-areas/$slug'
    | '/forms/$slug'
    | '/news/$slug'
    | '/p/$slug'
    | '/projects/$slug'
    | '/projects/map'
    | '/team/$id'
    | '/albums/'
    | '/articles/'
    | '/focus-areas/'
    | '/news/'
    | '/projects/'
    | '/admin/about'
    | '/admin/albums'
    | '/admin/articles'
    | '/admin/branding'
    | '/admin/contact'
    | '/admin/documents'
    | '/admin/focus-areas'
    | '/admin/forms'
    | '/admin/homepage'
    | '/admin/menu'
    | '/admin/news'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/tags'
    | '/admin/users'
    | '/admin/video-albums'
    | '/admin/'
    | '/admin/forms/'
    | '/admin/forms/$id/submissions'
    | '/admin/forms/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/partners'
    | '/reset-password'
    | '/resources'
    | '/setup'
    | '/albums/$slug'
    | '/articles/$slug'
    | '/focus-areas/$slug'
    | '/forms/$slug'
    | '/news/$slug'
    | '/p/$slug'
    | '/projects/$slug'
    | '/projects/map'
    | '/team/$id'
    | '/albums'
    | '/articles'
    | '/focus-areas'
    | '/news'
    | '/projects'
    | '/admin/about'
    | '/admin/albums'
    | '/admin/articles'
    | '/admin/branding'
    | '/admin/contact'
    | '/admin/documents'
    | '/admin/focus-areas'
    | '/admin/homepage'
    | '/admin/menu'
    | '/admin/news'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/tags'
    | '/admin/users'
    | '/admin/video-albums'
    | '/admin'
    | '/admin/forms'
    | '/admin/forms/$id/submissions'
    | '/admin/forms/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/partners'
    | '/reset-password'
    | '/resources'
    | '/setup'
    | '/albums/$slug'
    | '/articles/$slug'
    | '/focus-areas/$slug'
    | '/forms/$slug'
    | '/news/$slug'
    | '/p/$slug'
    | '/projects/$slug'
    | '/projects/map'
    | '/team/$id'
    | '/albums/'
    | '/articles/'
    | '/focus-areas/'
    | '/news/'
    | '/projects/'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/albums'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/focus-areas'
    | '/_authenticated/admin/forms'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stats'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/video-albums'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/forms/'
    | '/_authenticated/admin/forms/$id/submissions'
    | '/_authenticated/admin/forms/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PartnersRoute: typeof PartnersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SetupRoute: typeof SetupRoute
  AlbumsSlugRoute: typeof AlbumsSlugRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  FocusAreasSlugRoute: typeof FocusAreasSlugRoute
  FormsSlugRoute: typeof FormsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  PSlugRoute: typeof PSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsMapRoute: typeof ProjectsMapRoute
  TeamIdRoute: typeof TeamIdRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  FocusAreasIndexRoute: typeof FocusAreasIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$slug': {
      id: '/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/albums/$slug'
      preLoaderRoute: typeof AlbumsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus-areas/': {
      id: '/focus-areas/'
      path: '/focus-areas'
      fullPath: '/focus-areas/'
      preLoaderRoute: typeof FocusAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus-areas/$slug': {
      id: '/focus-areas/$slug'
      path: '/focus-areas/$slug'
      fullPath: '/focus-areas/$slug'
      preLoaderRoute: typeof FocusAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$slug': {
      id: '/forms/$slug'
      path: '/forms/$slug'
      fullPath: '/forms/$slug'
      preLoaderRoute: typeof FormsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/map': {
      id: '/projects/map'
      path: '/projects/map'
      fullPath: '/projects/map'
      preLoaderRoute: typeof ProjectsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/albums': {
      id: '/_authenticated/admin/albums'
      path: '/admin/albums'
      fullPath: '/admin/albums'
      preLoaderRoute: typeof AuthenticatedAdminAlbumsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/focus-areas': {
      id: '/_authenticated/admin/focus-areas'
      path: '/admin/focus-areas'
      fullPath: '/admin/focus-areas'
      preLoaderRoute: typeof AuthenticatedAdminFocusAreasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/forms': {
      id: '/_authenticated/admin/forms'
      path: '/admin/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AuthenticatedAdminFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/video-albums': {
      id: '/_authenticated/admin/video-albums'
      path: '/admin/video-albums'
      fullPath: '/admin/video-albums'
      preLoaderRoute: typeof AuthenticatedAdminVideoAlbumsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/forms/': {
      id: '/_authenticated/admin/forms/'
      path: '/'
      fullPath: '/admin/forms/'
      preLoaderRoute: typeof AuthenticatedAdminFormsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminFormsRoute
    }
    '/_authenticated/admin/forms/$id/': {
      id: '/_authenticated/admin/forms/$id/'
      path: '/$id'
      fullPath: '/admin/forms/$id/'
      preLoaderRoute: typeof AuthenticatedAdminFormsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminFormsRoute
    }
    '/_authenticated/admin/forms/$id/submissions': {
      id: '/_authenticated/admin/forms/$id/submissions'
      path: '/$id/submissions'
      fullPath: '/admin/forms/$id/submissions'
      preLoaderRoute: typeof AuthenticatedAdminFormsIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminFormsRoute
    }
  }
}

interface AuthenticatedAdminFormsRouteChildren {
  AuthenticatedAdminFormsIndexRoute: typeof AuthenticatedAdminFormsIndexRoute
  AuthenticatedAdminFormsIdSubmissionsRoute: typeof AuthenticatedAdminFormsIdSubmissionsRoute
  AuthenticatedAdminFormsIdIndexRoute: typeof AuthenticatedAdminFormsIdIndexRoute
}

const AuthenticatedAdminFormsRouteChildren: AuthenticatedAdminFormsRouteChildren =
  {
    AuthenticatedAdminFormsIndexRoute: AuthenticatedAdminFormsIndexRoute,
    AuthenticatedAdminFormsIdSubmissionsRoute:
      AuthenticatedAdminFormsIdSubmissionsRoute,
    AuthenticatedAdminFormsIdIndexRoute: AuthenticatedAdminFormsIdIndexRoute,
  }

const AuthenticatedAdminFormsRouteWithChildren =
  AuthenticatedAdminFormsRoute._addFileChildren(
    AuthenticatedAdminFormsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminAlbumsRoute: typeof AuthenticatedAdminAlbumsRoute
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminFocusAreasRoute: typeof AuthenticatedAdminFocusAreasRoute
  AuthenticatedAdminFormsRoute: typeof AuthenticatedAdminFormsRouteWithChildren
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVideoAlbumsRoute: typeof AuthenticatedAdminVideoAlbumsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminAlbumsRoute: AuthenticatedAdminAlbumsRoute,
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminFocusAreasRoute: AuthenticatedAdminFocusAreasRoute,
  AuthenticatedAdminFormsRoute: AuthenticatedAdminFormsRouteWithChildren,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
  AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVideoAlbumsRoute: AuthenticatedAdminVideoAlbumsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PartnersRoute: PartnersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SetupRoute: SetupRoute,
  AlbumsSlugRoute: AlbumsSlugRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  FocusAreasSlugRoute: FocusAreasSlugRoute,
  FormsSlugRoute: FormsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  PSlugRoute: PSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsMapRoute: ProjectsMapRoute,
  TeamIdRoute: TeamIdRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  FocusAreasIndexRoute: FocusAreasIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
